# Replace with your dgx environment
# Include only packages that are necessary for inference

name: env-name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.2
  - pandas=1.5.3
  - pip
  - pip:
      - tqdm